id: AB8B0CBA9
base_file: f9EC0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:12:08.183520
  last_modified_at: 2022-06-11 13:12:08.183524
